### ISSUE TITLE
Error upgrading to chef-workstation 21.2.278

### ISSUE THREAD

**Issue by harveymonster** [chef/homebrew-chef#169]
# Version:

chef-workstation 21.2.278

# Environment:

MacOS 10.15.7

# Scenario:

I was trying to use brew to upgrade the version of chef-workstation I have and it errored in the process.

# Steps to Reproduce:

brew upgrade chef-workstation                                        
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
Updated 3 casks.

==> Upgrading 1 outdated package:
chef-workstation 21.2.259 -> 21.2.278
==> Upgrading chef-workstation
==> Downloading https://packages.chef.io/files/stable/chef-workstation/21.2.278/mac_os_x/10.15/chef-workstation-21.2.278-1.dmg
######################################################################## 100.0%
==> Quitting application 'sh.chef.chef-workstation'...
Application 'sh.chef.chef-workstation' quit successfully.
==> Uninstalling packages:
com.getchef.pkg.chef-workstation
Password:
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit
==> Purging files for version 21.2.278 of Cask chef-workstation
Error: chef-workstation: Failure while executing; `/usr/bin/sudo -E -- /bin/chmod -- 777 /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-cli-3.1.1/lib/chef-cli/skeletons/code_generator/files/default/repo/cookbooks/example/recipes` exited with 1. Here's the output:
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit

# Expected Result:

chef-workstation to be upgrade

# Actual Result:

brew errored during the upgrade process

**Comment by tas50** [comment]
@harveymonster Can you try again now that we pushed a new version?

**Comment by harveymonster** [comment]
@tas50, I'm still running into trying to use brew to upgrade to the new version. Depending on how I tell brew to upgrade I get two different errors.

### Error 1:

The same error I originally reported.

~ brew upgrade chef-workstation                
==> Upgrading 1 outdated package:
chef-workstation 21.2.259 -> 21.2.278
==> Upgrading chef-workstation
==> Downloading https://packages.chef.io/files/stable/chef-workstation/21.2.278/mac_os_x/10.15/chef-workstation-21.2.278-1.dmg
Already downloaded: /Users/nathan.harvey/Library/Caches/Homebrew/downloads/97eb204a01a9d46c1f85ec6a09d68a164219d810c18202d8ff1ce0131b36cf9c--chef-workstation-21.2.278-1.dmg
==> Uninstalling packages:
com.getchef.pkg.chef-workstation
Password:
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit
==> Purging files for version 21.2.278 of Cask chef-workstation
Error: chef-workstation: Failure while executing; `/usr/bin/sudo -E -- /bin/rmdir -- /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.26.4/lib/plugins/inspec-init/templates/profiles/aws/controls` exited with 1. Here's the output:
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit

### Error 2:

~ brew upgrade
==> Casks with 'auto_updates' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
chef/chef/chef-workstation 21.2.259 -> 21.2.292
==> Upgrading chef-workstation
==> Downloading https://packages.chef.io/files/stable/chef-workstation/21.2.292/mac_os_x/10.14/chef-workstation-21.2.292-1.dmg

curl: (22) The requested URL returned error: 404 
==> Purging files for version 21.2.292 of Cask chef-workstation
Error: chef/chef/chef-workstation: Download failed on Cask 'chef-workstation' with message: Download failed: https://packages.chef.io/files/stable/chef-workstation/21.2.292/mac_os_x/10.14/chef-workstation-21.2.292-1.dmg

~ brew upgrade --casks         
==> Casks with 'auto_updates' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
chef/chef/chef-workstation 21.2.259 -> 21.2.292
==> Upgrading chef-workstation
==> Downloading https://packages.chef.io/files/stable/chef-workstation/21.2.292/mac_os_x/10.14/chef-workstation-21.2.292-1.dmg

curl: (22) The requested URL returned error: 404 
==> Purging files for version 21.2.292 of Cask chef-workstation
Error: chef/chef/chef-workstation: Download failed on Cask 'chef-workstation' with message: Download failed: https://packages.chef.io/files/stable/chef-workstation/21.2.292/mac_os_x/10.14/chef-workstation-21.2.292-1.dmg

**Comment by sabat** [comment]
This is happening because Chef changed its file naming convention to include '.x86_64' for both the dmg file and the pkg file. [This PR](https://github.com/chef/homebrew-chef/pull/172) fixes that.

**Comment by tas50** [comment]
Closing this out now that the PR is merged

**Comment by harveymonster** [comment]
@tas50, after the filename was updated, brew can download the new version. However, 21.2.292 is still failing to upgrade with the same error I saw when trying to upgrade to 21.2.278.

### Error:

~ brew upgrade                 
==> Casks with 'auto_updates' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
chef/chef/chef-workstation 21.2.259 -> 21.2.292
==> Upgrading chef-workstation
==> Downloading https://packages.chef.io/files/stable/chef-workstation/21.2.292/mac_os_x/10.14/chef-workstation-21.2.292-1.x86_64.dmg
Already downloaded: /Users/nathan.harvey/Library/Caches/Homebrew/downloads/a19e6c9bfaf8db069a998db33760e99e98501f95286b7dd0227753ae517e2bb6--chef-workstation-21.2.292-1.x86_64.dmg
==> Uninstalling packages:
com.getchef.pkg.chef-workstation
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit
==> Purging files for version 21.2.292 of Cask chef-workstation
Error: chef/chef/chef-workstation: Failure while executing; `/usr/bin/sudo -E -- /bin/chmod -- 777 /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-cli-3.1.1/lib/chef-cli/skeletons/code_generator/files/default/repo/data_bags` exited with 1. Here's the output:
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit

**Comment by harveymonster** [comment]
@tas50, can this issue be re-opened since the issue is still there with the updated version?

**Comment by tas50** [comment]
I'll get this escalated to our engineering team to see what might be causing this.

**Comment by harveymonster** [comment]
@tas50 , I've encountered this issue with other casks that require sudo, so maybe it's not a problem specific to chef-workstation. I submitted an issue (https://github.com/Homebrew/homebrew-cask/issues/100652) to homebrew-cask and wanted/cross-link here.

**Comment by tas50** [comment]
Thanks @harveymonster. This one really confuses me. It should just work

**Comment by lamont-granquist** [comment]
4294967295 is -1 and is probably the 32-bit uid/gid of the nobody user

**Comment by tjbikes** [comment]
See https://discussions.apple.com/thread/252518458 - reconnecting to AD fixed this issue for me.
